{% set version = "1.3.0" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: d4540617648cb5f895730f1ad8c82a65f2dad0166f57b75f3ca54759c4d67a85
  patches:
    # This should be able to be removed in the next release. 
    - patches/01_remove_type_checker.patch

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch  # [not win]
  host:
    - python
    - pip
    - wheel
    - setuptools
    - flit-core >=3.2,<4
  run:
    - python
    - python-dateutil >=2.7.0

test:
  imports:
    - arrow
  source_files:
    - tests
  requires:
    - dateparser ==1.*
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    # Pin `pytz` to match upstream. Prevents chance for version mismatch with `python-dateutils`
    - pytz ==2021.1
    - simplejson ==3.*
  commands:
    - pip check
    - pytest --cov tests/arrow

about:
  home: https://github.com/arrow-py/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Better dates & times for Python
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/arrow-py/arrow
  doc_url: https://arrow.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
