{% set name = "arrow" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed0cc050e98001b8779e84d461b0098c4ac597e88704a655582b21d116e526d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - python-dateutil >=2.7.0
    - backports.zoneinfo ==0.2.1  # [py<39]
    - python-tzdata  # [py>=39]

test:
  source_files:
    - tests
  imports:
    - arrow
  commands:
    - pip check
    - pytest -v tests
  requires:
    - dateparser ==1.*
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - pytz ==2025.2
    - simplejson ==3.*

about:
  home: https://github.com/arrow-py/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Better dates & times for Python
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/arrow-py/arrow
  doc_url: https://arrow.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
