{% set version = "0.10.0" %}
{% set gh_org = "crsmithdev" %}
{% set gh_repo = "arrow" %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ gh_repo[0] }}/{{ gh_repo }}/{{ gh_repo }}-{{ version }}.tar.gz
  sha256: 805906f09445afc1f0fc80187db8fe07670e3b25cdafa09b8d8ac264a8c0c722

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil

test:
  requires:
    - nose-cov
    - chai
    - simplejson
  commands:
    - nosetests "{{ environ['SRC_DIR'] }}"

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  summary: 'Better dates & times for Python.'

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
