travis:
  secure:
    BINSTAR_TOKEN: HuZB3f2Tg12TcRn6eQ+H41sCMbgxivyPGG3vu+Ma5b0NzchXXXCi24w8eWcR35BbLe9xnjFh5mmTLG1zZ0R2k96bjiqCI1m/4icS3/V1nerI63SFHVEHxP43PhBo65VU85RwQRNNmVl6GpUdMmCza+5PBh19KQvIUKkNlPz/2NojYO8cR445djlcRjf3sDDRXNzoYLETK9T1Tkkp2FfBcqq7LaIXHmyn+HxAx2faxcUHjrlR9baFrqv9nzQBXtOzmRIu0FylPE8jBWhKwpNgReo9DVCjGbWBxHb+xUQzAH6LpvDdn17piKYyopxjaREpsBkVQGxqtBuBNcq6iL7W4wsCMXOCstIwE6qVwR2YLzR61noAAMOGjYN7G3mP7kO4wY6tSWPJwHCSoC4rs+x4hKzg5BTme/7sbIgv9VSV2O3NDU8Ca7eqPRQlJdljE4k+nIJ71634m9v7SL8CQQvVtzC7uZmwKOk0OtNuYTNTfuV1ENkksOTF1yidPxPWLOD4co6sH6cXfiFiVMpgpOyTau4fvGQXjjwDhoc/1OYsdJgtY1IXRJXHCk76WoQ7qqbwELGpJ39JAhYR//x4/NOYh3PB1+NQtx8VlI0MID0jtjGyl0LcbWvhnakX7BEO6NKbgHkgTR5j9+dtQb+41v6Ysd7MdoYKDA2kZbPqD8vj1MY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
